### ISSUE TITLE
As a user when I use the search bar on the landing page I expect the results to be fuzzy and match relatively instead of precisely

### ISSUE THREAD

**Issue by Drew242** [Drew242/the_pivot#40]

**Comment by novohispano** [comment]
Fix the search functionality so that when I type only a city, I get all matching jobs, or if I type only the title, I get all the matching jobs.

**Comment by rickbacci** [comment]
Eric, this doesn't work. Please write tests and fix this. It is one of our base requirements for iteration 2 that must be completed.. Also please write a test or remove the pending test for the gem if we have good coverage already.
